### PR TITLE
[FW-137] Add turn_on() method to PWMSensor

### PR DESCRIPTION
**Pull request by jdmarmen**
PWMSensor inscribed an InputCapture pin but did not include the call to the turn_on() method, so it was not working.

### CODE REVIEW

**Review by g0nz4I0 — CHANGES_REQUESTED** [review]
I dont think this works, can you add some tests to PWMSensor, if I remember correctly turn_ons must be performed **AFTER** `STLIB::start()`, and the inscribe needs to be performed before `STLIB::start()` so this solution is incompatible. 

Again, try to make a test and check it

**Comment by oganigl** [comment]
I think the best idea might be two methods to turn_on and turn_off the pwm_sensor. So you have control of the pwm sensor and you can construct before but do the turn on after

**Comment by jdmarmen** [comment]
> I dont think this works, can you add some tests to PWMSensor, if I remember correctly turn_ons must be performed **AFTER** `STLIB::start()`, and the inscribe needs to be performed before `STLIB::start()` so this solution is incompatible.
> 
> Again, try to make a test and check it

I've done a small the test with the python and works correctly, the sensor is declared before start()

**Review by g0nz4I0 — CHANGES_REQUESTED** [review]
I'm still not approving it, I looked at it further and it should be done like this;

image

See that LinearSensor does not have a turn_on method, yet the ADC does and it gets called, so its just a matter of calling it at the same time, this way we are consistent,

**Review by jmaralo — CHANGES_REQUESTED** [review]
Creating a sensor shouldn't turn it on, it should be a separate action. More or less what gonzalo already said

**Review by g0nz4I0 — APPROVED** [review]

**Pull request merged**
