### PR TITLE
feature/fix build script

### PR DESCRIPTION
**Pull request by g0nz4I0**
Fixed CMake error on post build on Windows and removed absolute path for nosys.specs file, also Windows build is now supported

### CODE REVIEW

**Comment by AmancioG** [comment]
You can use:
 
       import os
       path = os.path.join(arg1, arg2, arg3, ... )

and writting the path in the arguments, you will get the OS default direcotry separator automatically. For example:

path = os.path.join("folder1", "folder2", "forlder3", "file")

path, on posix systems, will be:
       "folder/folder2/folder3/file"

and on Windows, it will instead be:
        "folder\folder2\folder3\file"

**Comment by g0nz4I0** [comment]
Addressed, this would have made it much easier from the beginning: I don't know why I didn't use it :(

**Comment by g0nz4I0** [comment]
Test slack bot

**Review by ricardochust — APPROVED** [review]

**Comment by ricardochust** [comment]
it works on my machine 👍

**Review by AmancioG — APPROVED** [review]

**Pull request merged**
